### ISSUE TITLE
Vendor directory should be configurable

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/pip-install#19]
We should consider making the pip vendor directory configurable through an environment variable. The `pip download` command supports this through a `--dest` flag.

**Comment by robdimsdale** [comment]
Sounds reasonable. I would suggest this could be configured via the environment variable: `BP_PIP_DEST_PATH`, and we should consider it to be a relative path to the working directory. If the environment variable is unset the value should default to: `./vendor`.

**Comment by joshuatcasey** [comment]
@robdimsdale I recommend one change from above:

If `BP_PIP_DEST_PATH` is unset, I recommend we provide no `--dest` flag to `pip download` and let that command decide where to download this files. Current tooling behavior is to use `./vendor`, but I recommend we don't try to bake that into this buildpack.
